// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Database = 1,
  Table = 3,
  TableName = 4,
  Column = 6,
  ColumnName = 7,
  ColumnType = 8,
  Constraint = 9,
  Relationship = 10
