// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Database = 1,
  Table = 3,
  TableName = 4,
  Icon = 5,
  IconName = 6,
  Column = 8,
  ColumnName = 9,
  ColumnType = 10,
  Constraint = 11,
  Relationship = 12
