// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {MiroStyleTags} from "../highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$[OVQPOOO[QPO'#C^QOQPOOOaQQO,58xOiQSO'#C`OnQPO'#ClOOQO1G.d1G.dOvQPO1G.dO{QWO,58zO!ZQQO'#CfO!fQPO,59WOOQO7+$O7+$OO!nQWO'#CmO!|QPO'#CdOOQO1G.f1G.fO#RQPO1G.fOOQO,59Q,59QOOQO-E6d-E6dOOQO'#Ce'#CeO#^QWO,59XO#lQPO,59OOOQO7+$Q7+$QOOQO-E6c-E6cO#qQQO1G.jOOQO7+$U7+$U",
  stateData: "#v~O]OS~ORPO~O_RO~OTSO^UO~OUWO~OdXO^`X~O^ZO~OV[Ob]O^SadSa~OTSO^YXdYX~OdXO^`a~OVbO^aXbaXdaX~ORdO~Ob]O^SidSi~OVbO^aabaadaa~OcgO~OThO~O",
  goto: "!UbPPcPfPPPlrxPPPPP!O!RRQOQTRR`XQ^WRe_Qc[RfcQYTRaYRVRR_W",
  nodeNames: "⚠ Database Table TableName Column ColumnName ColumnType Constraint Relationship",
  maxTerm: 20,
  propSources: [MiroStyleTags],
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "#R~R[XYwYZw]^wpqw|}|}!O!R!O!P!^!c!}!c#R#S!c#T#o!c#o#p!w#q#r!|~|O]~~!ROd~~!UP!`!a!X~!^Ob~~!cOc~_!nRTQUSVWRP!c!}!c#R#S!c#T#o!c~!|O_~~#RO^~",
  tokenizers: [0, 1, 2, 3],
  topRules: {"Database":[0,1]},
  tokenPrec: 0
})
