// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Database = 1,
  Table = 2,
  TableName = 3,
  Column = 4,
  ColumnName = 5,
  ColumnType = 6,
  Constraint = 7,
  Relationship = 8
